### ISSUE TITLE
Publishing kanban-example

### ISSUE THREAD

**Issue by hackerwins** [dc7303/kanban-example#1]
How about distributing this example using Netlify or gh-pages?

**Comment by dc7303** [comment]
@hackerwins I think it's a good idea. I will work on it soon. :)

I made this example to study how to use `vue` and `yorkie` together, but if you think that this example is useful, you can copy it to the `yorkie-team` project and make it. I think doing this will allow more people to use this example.  
If you have different thoughts with me, I will manage this example in my account.

**Comment by hackerwins** [comment]
I think this example useful. But we have to think that if it is moved to the org repository, it has to be maintained by maintainers. For now, I'm the only maintainer of Yorkie and I'm not familiar with Vue.js yet, so it would be nice to think about moving this repository to org after the community grows.

**Comment by dc7303** [comment]
@hackerwins Thanks for answer. I will reflect your suggestions soon :)

**Comment by dc7303** [comment]
@hackerwins Currently, I am not using a cloud server.
So.. Can I use `https://yorkie.dev/api` resource?

**Comment by hackerwins** [comment]
Sure. :)
